/** This code is property of the Corundum project managed under the Software Developers' Association of Arizona State University.
 *
 * Copying and use of this open-source code is permitted provided that the following requirements are met:
 *
 * - This code may not be used or distributed for private enterprise, including but not limited to personal or corporate profit. - Any products resulting from the copying,
 * use, or modification of this code may not claim endorsement by the Corundum project or any of its members or associates without written formal permission from the endorsing
 * party or parties. - This code may not be copied or used under any circumstances without the inclusion of this notice and mention of the contribution of the code by the
 * Corundum project. In source code form, this notice must be included as a comment as it is here; in binary form, proper documentation must be included with the final product
 * that includes this statement verbatim.
 * 
 * @author REALDrummer */

package utils;

public class myWiki {
    // material names
    public static final String[][] ENCHANTMENT_IDS = {
            { "Protection", "Environmental Protection", "normal Protection", "regular Protection", "general Protection" },
            { "Fire Protection", "lava protection", "burn protection", "magma protection" },
            { "Feather Falling", "falling protection", "landing protection", "soft shoes", "shoes", "boots" },
            { "Blast Protection", "explosion protection", "Creeper protection", "T.N.T. TNT protection" },
            { "Projectile Protection", "arrow protection", "skeleton protection" },
            { "Respiration", "extra breathingunderwater", "SCUBA gear", "increase lung capacity", "air bubble" },
            { "Aqua Affinity", "underwater worker", "underwater miner", "underwater digger" },
            { "Thorns", "reflect damage", "spiky armor", "chestplates" },
            { "Sharpness", "extra sword damage" },
            { "Smite", "undead killer", "zombie killer", "skeleton killer", "zombie pigmen killer", "zombie pigman killer", "extra sword damage to undead",
                    "extra sword damage to zombies", "extra sword damage to skeletons", "extra sword damage to skeles", "extra sword damage to zombie pigman",
                    "extra sword damage to zombie pigmen" },
            { "Bane of Arthropods", "cave spider killer", "extra sword damage to cave spiders" },
            { "Knockback", "sword throwback" },
            { "Fire Aspect", "sword flame", "fire sword", "fire" },
            { "Looting", "extra drops", "more rare drops", "more items", "extra items", "extra loots" },
            { "Efficiency", "efficeincy", "haste", "hasty mining", "hasty digging", "fast mining", "fast digging", "quickly digging", "quickly mining" },
            { "Silk Touch", "ice getter", "grass getter", "soft toucher", "soft miner", "soft digger", "careful miner", "careful digger" },
            { "Unbreaking", "longer life living", "more durability", "extra durability", "extra item health", "more item health", "longer lasting items" },
            { "Fortune", "more mining drops", "extra ores", "extra valuables", "extra diamonds", "extra gems", "more ores", "more valuables", "more diamonds", "more gems",
                    "riches" },
            { "Power", "extra bow damage", "stopping power", "stronger arrows", "extra arrow damage", "more bow damage", "more arrow damage", "sharpness arrows",
                    "sharper arrows" }, { "Punch", "knockback bows", "bows throwback" },
            { "Flame", "fire aspect bow", "flame bow", "flaming arrows", "fire aspect arrows", "incendiary rounds", "incendiary bows", "incendiary arrows" },
            { "Infinity", "infinite ammo", "endless ammo", "infinite ammunitions", "endless ammunitions", "one arrow infinite arrows", "one arrow endless infinite arrows" },
            { "Luck of the Sea", "fishing rod looting", "better fish", "fish more items" },
            { "Lure", "faster fishing", "efficiency fishing rod", "speed fishing", "better bait fishing" } };
    public static final String[][][] ENTITY_IDS =
            {
                    null,
                    { { "dropped items", "a dropped item", "miniblocks", "miniitems", "floating dropped thrown chucked tossed stuff things miniblocks miniitems" } },
                    { { "experience orbs", "an experience orb", "experience balls" } },
                    { { "lead knots", "a lead knot", "a leash knots", "a tie knots", "a rope knots" } },
                    { { "paintings", "a painting", "wall framed paintings" } },
                    { { "flying arrows", "a flying arrow", "shot fired arrows" } },
                    { { "thrown snowballs", "a thrown snowball", "chucked tossed thrown snowballs balls of snow" } },
                    { { "Ghast fireballs", "a Ghast fireball", "Ghast fired shot fireballs cannonballs explosive exploding fire charges" } },
                    { { "Blaze fireballs", "a Blaze fireball", "Blaze fired shot fireballs cannonballs explosive exploding fire charges" } },
                    { { "thrown Ender Pearls", "a thrown Ender Pearl", "Enderman Endermen thrown chucked fired Ender Pearls Enderpearls" } },
                    { { "thrown Eyes of Ender", "a thrown Eye of Ender", "Enderman Endermen thrown chucked fired Eyes of Ender Endereyes" } },
                    { { "thrown splash potions", "a thrown splash potion", "thrown chucked fired used potions pots" } },
                    { { "thrown Bottles o' Enchanting", "a thrown Bottle o' Enchanting", "xp bottle",
                            "thrown chucked fired used Bottles glasses o' of Enchanting experience levels" } },
                    { { "item frames", "an item frame" } },
                    { { "Wither skull projectiles", "a Wither skull projectile", "Wither bosses boss's skulls projectiles fired heads explosives exploding" } },
                    { { "T.N.T.", "some T.N.T.", "primed T.N.T.", "lit T.N.T.", "activated T.N.T.", "primed TNT", "lit TNT", "activated TNT", "primed trinitrotoluene",
                            "lit trinitrotoluene", "activated trinitrotoluene" } },
                    { { "falling blocks", "a falling block", "falling gravel", "falling sand", "falling anvils", "falling dragon eggs" } },
                    { { "fireworks", "a firework", "firework rockets" } },
                    { { "boats", "a boat", "dinghies", "dinghys", "ships" } },
                    { { "minecarts", "a minecart" } },
                    { { "storage minecarts", "a storage minecart", "minecrafts with storage", "minecarts with chests" } },
                    { { "powered minecarts", "a powered minecart", "gas powered minecarts", "coal powered minecarts", "furnace minecarts" } },
                    { { "T.N.T. minecarts", "a T.N.T. minecart", "explosive minecarts", "TNT minecarts", "trinitrotoluene minecarts" } },
                    { { "hopper minecarts", "a hopper minecart", "minecarts with hoppers", "vacuum minecarts" } },
                    { { "spawner minecarts", "a spawner minecart", "minecarts with spawners", "minecarts with monster spawners" } },
                    { { "generic mobs", "a generic mob", "mobs" } },
                    { { "generic monsters", "a generic monster", "monsters" } },
                    {
                            { "creepers", "a creeper", "exploding green penis monsters", "explosive green penis monsters" },
                            { "non-charged creepers", "a non-charged creeper", "unpowered regular normal average run-of-the-mill exploding explosive green penis monsters" },
                            { "charged creepers", "a charged creeper", "lightninged struck exploding green penis monsters",
                                    "lightninged struck explosive green penis monsters" } },
                    { { "skeletons", "a skeleton", "skeles", "skeleton archers" }, { "skeletons", "a skeleton", "skeles", "skeleton archers" },
                            { "Wither skeletons", "a Wither skeleton", "Wither skeles", "Wither skeletons", "swordsman skeletons", "swordsman skeles" } },
                    { { "spiders", "a spider", "giant spiders" } },
                    { { "giants", "a giant", "giant zombies" } },
                    { { "zombies", "a zombie" } },
                    { { "slimes", "a slime", "slime cubes", "living slime" } },
                    { { "Ghasts", "a Ghast", "giant floating jellyfish", "giant flying jellyfish", "giant floating squids", "giant flying squids" } },
                    { { "zombie pigmen", "a zombie pigman", "zombie pigman", "pigman zombies" } },
                    { { "Endermen", "Enderman" } },
                    { { "cave spiders", "a cave spider", "small spiders", "poisonous spiders", "venomous spiders" } },
                    { { "silverfish", "a silverfish", "bugs", "stronghold silverfish", "stronghold bugs" } },
                    { { "Blazes", "a Blaze", "Nether dungeon guards", "Nether stronghold guards", "Nether dungeon monsters", "Nether stronghold monsters" } },
                    { { "Magma Cubes", "a Magma Cube", "lava cubes", "Nether slimes", "living magma", "living lava" } },
                    { { "The Ender Dragon", "the big black scary dragon" } },
                    { { "The Wither", "The Wither", "The Wither boss" } },
                    { { "bats", "a bat" } },
                    { { "witches", "a witch", "wicked witches" } },
                    { { "pigs", "a pig", "piggies", "piglets" } },
                    { { "sheep", "a sheep", "lambs" }, { "white sheep", "a white sheep", "white lambs" }, { "orange sheep", "an orange sheep", "orange lambs" },
                            { "magenta sheep", "a magenta sheep", "magenta lambs" }, { "light blue sheep", "a light blue sheep", "light blue lambs" },
                            { "yellow sheep", "a yellow sheep", "yellow lambs" }, { "lime green sheep", "a lime green sheep", "lime green lambs" },
                            { "pink sheep", "a pink sheep", "pink lambs" },
                            { "gray sheep", "a gray sheep", "dark gray sheep", "dark grey sheep", "dark gray lambs", "dark grey lambs" },
                            { "light gray sheep", "a light gray sheep", "light gray lambs" }, { "cyan sheep", "a cyan sheep", "cyan lambs" },
                            { "purple sheep", "a purple sheep", "purple lambs" }, { "blue sheep", "a blue sheep", "dark blue sheep", "dark blue lambs" },
                            { "brown sheep", "a brown sheep", "brown lambs" },
                            { "cactus green sheep", "a cactus green sheep", "dark green sheep", "cactus green lambs", "dark green lambs" },
                            { "red sheep", "a red sheep", "red lambs" }, { "black sheep", "a black sheep", "black lambs", "nun sheep" } },
                    { { "cows", "a cow" } },
                    { { "chickens", "a chicken", "chicks" } },
                    { { "squid", "a squid", "squids", "octopi", "octopuses" } },
                    { { "wolves", "a wolf", "dogs", "wolfs", "hounds" } },
                    { { "mooshrooms", "a mooshroom", "mooshroom cows" } },
                    { { "snow golems", "a snow golem", "living snowmen" } },
                    { { "ocelots", "an ocelot", "jungle cats" } },
                    { { "iron golems", "an iron golem", "N.P.C. village guards", "NPC village guards", "Testificates village guards" } },
                    {
                            { "villagers", "a villager", "N.P.C.s", "NPCs", "Testificates" },
                            { "farmer villagers", "a farmer villager", "farmers villagers", "farmers N.P.C.s", "farmers NPCs", "farmers Testificates" },
                            { "librarian villagers", "a librarian villager", "librarians villagers", "librarians N.P.C.s", "librarians NPCs", "librarians Testificates" },
                            { "priest villagers", "a priest villager", "Minecraft priests villagers", "Minecraft priests N.P.C.s", "Minecraft priests NPCs",
                                    "Minecraft priests Testificates" },
                            { "butcher villagers", "a butcher villager", "butchers villagers", "butcher N.P.C.s", "butcher NPCs", "butcher testificates" },
                            { "blacksmith villagers", "a blacksmith villager", "blacksmiths villagers", "blacksmiths N.P.C.s", "blacksmiths NPCs", "blacksmiths Testificates" },
                            { "zombie villagers", "a zombie villager", "zombies villagers", "zombies N.P.C.s", "zombies NPCs", "zombies Testificates", "zombified villagers",
                                    "zombified N.P.C.s", "zombified NPCs", "zombified Testificates" } },
                    { { "Ender crystals", "an Ender crystal", "Ender Dragon shield generators" } } };
    public static final String[][][] ITEM_IDS =
            {
                    { { "air", "some air" } },
                    { { "stone", "some stone", "rock", "smooth stone" } },
                    { { "grass", "some grass", "grass blocks" } },
                    {
                            { "dirt", "some dirt", "filth" },
                            { "grassless dirt", "some grassless dirt", "dirt without grass", "dirt with no grass", "filth without grass" },
                            { "podzol", "some podzol", "forest floor", "pine needles", "acid dirt", "acid soil", "dirty grass", "dead leaves", "fallen leaves",
                                    "pine droppings" } },
                    { { "cobblestone", "some cobblestone", "cobblies" } },
                    { { "wooden planks", "some wooden planks", "planks" }, { "oak planks", "some oak planks", "oak wooden planks" },
                            { "spruce planks", "some spruce planks", "spruce wooden planks", "pine planks", "pine wooden planks" },
                            { "birch planks", "some birch planks", "birch wooden planks" }, { "jungle planks", "some jungle planks", "jungle wooden planks" },
                            { "acacia planks", "some acacia planks", "acacia wooden planks" },
                            { "dark oak planks", "some dark oak planks", "dark oak wooden planks", "big large dark big huge old ancient oak wooden planks" } },
                    { { "saplings", "a sapling" }, { "oak saplings", "an oak sapling", "oak tree saplings" },
                            { "spruce saplings", "a spruce sapling", "spruce tree saplings", "pine tree saplings" },
                            { "birch saplings", "a birch sapling", "birch tree saplings" }, { "jungle saplings", "a jungle sapling", "jungle tree saplings" },
                            { "acacia saplings", "an acacia sapling", "acacia tree saplings" },
                            { "dark oak saplings", "a dark oak sapling", "some dark big large huge old ancient oak tree saplings" } },
                    { { "bedrock", "some bedrock" } },
                    { { "water", "some water" } },
                    { { "stationary water", "some stationary water", "immobile water", "nonspreadable water" } },
                    { { "lava", "some lava" } },
                    { { "stationary lava", "some stationary lava", "immobile lava", "nonspreadable lava" } },
                    { { "sand", "some sand" }, { "red sand", "some red sand", "new mesa sand" } },
                    { { "gravel", "some gravel", "pebbles" } },
                    { { "gold ore", "some gold ore", "golden ore" } },
                    { { "iron ore", "some iron ore" } },
                    { { "coal ore", "some coal ore" } },
                    { { "logs", "a log", "wood" }, { "oak logs", "an oak log", "oak wood" }, { "spruce logs", "a spruce log", "spruce wood", "pine logs", "pine wood" },
                            { "birch logs", "a birch log", "birch wood" }, { "jungle logs", "a jungle log", "jungle wood" } },
                    {
                            { "leaves", "some leaves", "leaves blocks", "leafs blocks" },
                            { "oak leaves", "some oak leaves", "oak leaves blocks", "oak leafs blocks" },
                            { "spruce leaves", "some spruce leaves", "spruce leaves blocks", "spruce leafs blocks", "pine needles", "pine leaves blocks", "pine leafs blocks" },
                            { "birch leaves", "some birch leaves", "birch leaves blocks", "birch leafs blocks" },
                            { "jungle leaves", "some jungle leaves", "jungle leaves blocks", "jungle leafs blocks" },
                            { "acacia leaves", "some acacia leaves", "acacia leaves blocks", "acacia leafs blocks" },
                            { "dark oak leaves", "some dark oak leaves", "dark big large huge old ancient oak leafs leaves blocks" } },
                    { { "sponges", "a sponge", "loofas" } },
                    { { "glass", "some glass", "glass blocks", "glass cubes" } },
                    { { "lapis lazuli ore", "some lapis lazuli ore" } },
                    { { "lapis lazuli blocks", "a lapis lazuli block", "blocks of lapis lazuli" } },
                    { { "dispensers", "a dispenser", "shooters" } },
                    {
                            { "sandstone", "some sandstone", "sandbricks" },
                            { "regular sandstone", "some regular sandstone", "regular sandbricks", "normal sandstone", "normal sandbricks", "natural sandstone",
                                    "natural sandbricks" },
                            { "chiseled sandstone", "some chiseled sandstone", "chiseled sandbricks", "ancient sandstone", "ancient sandbricks", "pyramid sandstone",
                                    "pyramid sandbricks", "hieroglyphics sandstone", "hieroglyphics sandbricks" },
                            { "smooth sandstone", "some smooth sandstone", "smooth sandbricks", "clean sandstone", "clean sandbricks" } },
                    { { "note blocks", "a note block", "music blocks", "sound blocks", "speakers" } },
                    { { "beds", "a bed" } },
                    { { "powered rails", "a powered rail", "powered redstone rails", "powered redstone tracks", "powered redstone railroad tracks" } },
                    { { "detector rails", "a detector rail", "detection rails", "sensor rails", "sensory rails", "pressure rails", "pressure plate rails",
                            "detector railroad tracks", "detection railroad tracks", "sensor railroad tracks", "sensory railroad tracks", "pressure railroad tracks",
                            "pressure plate railroad tracks" } },
                    { { "sticky pistons", "a sticky piston", "slime pistons", "slimy pistons" } },
                    { { "cobwebs", "a cobweb", "spider webs", "webs" } },
                    { { "tall grass and dead shrubs", "some tall grass or a dead shrub", "tall grass and dead shrubbery", "weeds" },
                            { "dead grass", "some dead grass", "dead grass bushes", "dead grass shrubs", "dead grass shrubbery" }, { "tall grass", "high grass" },
                            { "ferns", "a fern", "small plants" } },
                    { { "dead shrubs", "a dead shrub", "dead bushes", "dead shrubbery", "dried plants" } },
                    { { "pistons", "a piston" } },
                    { { "piston arms", "a piston arm", "piston extensions", "piston pusher" } },
                    { { "wool", "some wool", "wool blocks" }, { "white wool", "some white wool", "white wool blocks" },
                            { "orange wool", "some orange wool", "orange wool blocks" }, { "magenta wool", "some magenta wool", "magenta wool blocks" },
                            { "light blue wool", "some light blue wool", "light blue wool blocks" }, { "yellow wool", "some yellow wool", "yellow wool blocks" },
                            { "lime green wool", "some lime green wool", "lime green wool blocks", "green wool blocks", "light green wool blocks" },
                            { "pink wool", "some pink wool", "pink wool blocks" }, { "gray wool", "some gray wool", "dark gray wool blocks" },
                            { "light gray wool", "some light gray wool", "light gray wool blocks", "off white wool blocks" },
                            { "cyan wool", "some cyan wool", "cyan wool blocks" }, { "purple wool", "some purple wool", "purple wool blocks" },
                            { "blue wool", "some blue wool", "dark blue wool blocks" }, { "brown wool", "some brown wool", "brown wool blocks" },
                            { "cactus green wool", "some cactus green wool", "cactus green wool blocks", "dark green wool blocks" },
                            { "red wool", "some red wool", "red wool blocks" }, { "black wool", "some black wool", "black wool blocks" } },
                    { { "blocks moved by pistons", "a block moved by a piston" } },
                    { { "dandelions", "a dandelion", "yellow flowers" } },
                    { { "flowers (except dandelions)", "a flower (not a dandelion)", "flowers that's aren't dandelions", "non-dandelion flowers", "flowers" },
                            { "poppies", "a poppy", "new roses" }, { "blue orchids", "a blue orchid", "blue flowers", "bluebells" },
                            { "alliums", "an allium", "allium flowers", "allia flowers", "purple flowers" }, { "red tulips", "a red tulip", "red flowers" },
                            { "orange tulips", "an orange tulip", "orange flowers" }, { "white tulips", "a white tulip", "white flowers" },
                            { "pink tulips", "a pink tulip", "pink flowers" }, { "oxeye daisies", "an oxeye daisy", "wild daisies", "wildflowers" } },
                    { { "brown mushrooms", "a brown mushroom", "small brown mushrooms", "little brown mushrooms" } },
                    { { "red mushrooms", "a red mushroom", "small red mushrooms", "little red mushrooms" } },
                    { { "gold blocks", "a gold block", "blocks of gold" } },
                    { { "iron blocks", "an iron block", "blocks of iron" } },
                    {
                            { "all non-wood double slab blocks", "a non-wood double slab block", "all non-wood double slabs", "all non-wood stacked slabs" },
                            { "stone double slab blocks", "a stone double slab block", "stone double slabs", "stone stacked slabs" },
                            { "sandstone double slab blocks", "a sandstone double slab block", "sandstone double slabs", "sandstone stacked slabs",
                                    "sandbrick double slab blocks", "sandbrick double slabs", "sandbrick stacked slabs" },
                            { "wooden double slab blocks [obsolete]", "a wooden double slab block [obsolete]" },
                            { "cobblestone double slab blocks", "a cobblestone double slab block", "cobblestone double slabs", "cobblestone stacked slabs" },
                            { "brick double slab blocks", "a brick double slab block", "clay brick stacked slabs", "clay brick double slab blocks", "clay brick double slabs" },
                            { "stone brick double slab blocks", "a stone brick double slab block", "stone brick double slabs", "stone brick stacked slabs" },
                            { "Nether brick double slab blocks", "a Nether brick double slab block", "Nether brick double slabs", "Nether brick stacked slabs" },
                            { "Nether Quartz double slab blocks", "a Nether Quartz double slab block", "Nether Quartz double slabs", "Nether Quartz stacked slabs" } },
                    { { "all non-wood slabs", "a non-wood slab", "all non-wood half blocks" }, { "stone slabs", "a stone slab", "stone half blocks" },
                            { "sandstone slabs", "a sandstone slab", "sandstone half blocks", "sandbrick slabs", "sandbrick half blocks" },
                            { "wooden slabs [obsolete]", "a wooden slab [obsolete]" }, { "cobblestone slabs", "a cobblestone slab", "cobblestone half blocks" },
                            { "brick slabs", "a brick slab", "clay brick slabs", "clay brick half blocks" },
                            { "stone brick slabs", "a stone brick slab", "stone brick half blocks" },
                            { "Nether brick slabs", "a Nether brick slab", "Nether brick half blocks" },
                            { "Nether Quartz slabs", "a Nether Quartz slab", "Nether Quartz half blocks" } },
                    { { "bricks", "some bricks", "bricks blocks" } },
                    { { "T.N.T.", "some T.N.T.", "TNT", "dynamite", "trinitrotoluene" } },
                    { { "bookcases", "a bookcase", "bookshelves", "bookshelfs" } },
                    { { "mossy stone", "some mossy stone", "mossy cobblestone", "ancient cobblestone", "old cobblestone" } },
                    { { "obsidian", "some obsidian", "volcanic glass" } },
                    { { "torches", "a torch", "fire sticks" } },
                    { { "fire", "a fire", "flames" } },
                    { { "monster spawners", "a monster spawner", "spawners" } },
                    { { "oak stairs", "some oak stairs", "oak wood stairs", "wooden stairs", "oak wood steps", "wooden steps" } },
                    { { "chests", "a chest" } },
                    { { "redstone wire", "a piece of redstone wire", "wire" } },
                    { { "diamond ore", "some diamond ore" } },
                    { { "diamond blocks", "a diamond block", "blocks of diamonds" } },
                    { { "crafting tables", "a crafting table", "crafting workbench" } },
                    { { "wheat", "some wheat", "crops" } },
                    { { "farmland blocks", "some farmland", "plowed tilled land soil blocks" } },
                    { { "furnaces", "a furnace", "ovens", "ranges" } },
                    { { "burning furnaces", "a burning furnace", "active burning ovens ranges furnaces" } },
                    { { "sign posts", "a sign post", "ground sign posts" } },
                    { { "wooden doors", "a wooden door", "doors" } },
                    { { "ladders", "a ladder", "wooden rope ladders" } },
                    { { "rails", "a rail", "normal regular unpowered iron rails railroad tracks" } },
                    { { "cobblestone stairs", "some cobblestone stairs", "cobblestone steps" } },
                    { { "wall signs", "a wall sign", "posted wall signs" } },
                    { { "levers", "a lever", "switches" } },
                    { { "stone pressure plates", "a stone pressure plate", "stone foot switches plates" } },
                    { { "iron doors", "an iron door" } },
                    { { "wooden pressure plates", "a wooden pressure plate", "wooden foot switches plates" } },
                    { { "redstone ore", "some redstone ore" } },
                    { { "glowing redstone ore", "some glowing redstone ore", "luminescent redstone ore" } },
                    { { "inactive redstone torches", "an inactive redstone torch" } },
                    { { "redstone torches", "a redstone torch" } },
                    { { "stone buttons", "a stone button", "buttons" } },
                    { { "snow on the ground", "some snow on the ground", "snow", "snow on the ground", "fallen snow", "fresh snow", "ground snow" } },
                    { { "ice", "some ice", "blocks of ice", "ice blocks" } },
                    { { "snow blocks", "a snow block", "blocks of snow" } },
                    { { "cacti", "a cactus", "cactuses", "saguaros", "saguaro cacti", "saguaro cactuses" } },
                    { { "clay blocks", "a clay block", "blocks of clay" } },
                    { { "sugar cane", "some sugar cane", "sugar canes", "sugarcanes" } },
                    { { "jukeboxes", "a jukebox", "disc player", "music box", "slotted block", ".mp3 player" } },
                    { { "wooden fences", "a wooden fence post", "wooden fence posts", "wooden railings" } },
                    { { "pumpkins", "a pumpkin", "unlit Jack-o'-Lanterns", "dark Jack-o'-Lanterns" } },
                    { { "Netherrack", "some Netherrack", "Nether rack", "Nether dirt" } },
                    { { "Soul Sand", "some Soul Sand", "Nether sand", "quicksand", "quick sand" } },
                    { { "glowstone", "some glowstone", "glowstone blocks", "blocks of glowstone" } },
                    { { "Nether portal blocks", "a Nether portal block", "Nether portal swirly blocks" } },
                    { { "Jack-o'-Lanterns", "a Jack-o'-Lantern", "lit Jack-o'-Lanterns", "lit Jack o Lanterns", "lit JackoLanterns" } },
                    { { "cakes", "a cake", "cake blocks" } },
                    { { "repeaters", "a repeater", "diodes", "delayers", "redstone repeaters", "redstone diodes", "redstone delayers" } },
                    { { "active repeaters", "an active repeater", "active diodes", "active delayers", "active redstone repeaters", "active redstone diodes",
                            "active redstone delayers" } },
                    {
                            { "stained glass", "some stained glass", "colored glass", "church glass", "tinted glass" },
                            { "white stained glass", "some white stained glass", "white colored glass", "white church glass", "white tinted glass" },
                            { "orange stained glass", "some orange stained glass", "orange colored glass", "orange church glass", "orange tinted glass" },
                            { "magenta stained glass", "some magenta stained glass", "magenta colored glass", "magenta church glass", "magenta tinted glass" },
                            { "light blue stained glass", "some light blue stained glass", "light blue colored glass", "light blue church glass", "light blue tinted glass" },
                            { "yellow stained glass", "some yellow stained glass", "yellow colored glass", "yellow church glass", "yellow tinted glass" },
                            { "lime green stained glass", "some lime green stained glass", "lime green colored glass", "lime green church glass", "lime green tinted glass" },
                            { "pink stained glass", "some pink stained glass", "pink colored glass", "pink church glass", "pink tinted glass" },
                            { "gray stained glass", "some gray stained glass", "gray colored glass", "gray church glass", "gray tinted glass" },
                            { "light gray stained glass", "some light gray stained glass", "light gray colored glass", "light gray church glass", "light gray tinted glass" },
                            { "cyan stained glass", "some cyan stained glass", "cyan colored glass", "cyan church glass", "cyan tinted glass" },
                            { "purple stained glass", "some purple stained glass", "purple colored glass", "purple church glass", "purple tinted glass" },
                            { "blue stained glass", "some blue stained glass", "blue colored glass", "blue church glass", "blue tinted glass" },
                            { "brown stained glass", "some brown stained glass", "brown colored glass", "brown church glass", "brown tinted glass" },
                            { "cactus green stained glass", "some cactus green stained glass", "cactus green colored glass", "cactus green church glass",
                                    "cactus green tinted glass" },
                            { "red stained glass", "some red stained glass", "red colored glass", "red church glass", "red tinted glass" },
                            { "black stained glass", "some black stained glass", "black colored glass", "black church glass", "black tinted glass" } },
                    { { "trapdoors", "a trapdoor", "ground doors" } },
                    { { "monster egg blocks", "a monster egg block", "monster eggs", "silverfish spawners" },
                            { "monster egg stone blocks", "a monster egg stone block", "monster egg stone", "silverfish stone", "silverfish smooth stone" },
                            { "monster egg cobblestone blocks", "a monster egg cobblestone block", "silverfish cobblestone" },
                            { "monster egg stone brick blocks", "a monster egg stone brick block", "monster egg stone bricks", "silverfish stone bricks" } },
                    { { "stone bricks", "some stone brick", "cobblestone bricks", "cobble bricks" },
                            { "stone bricks", "some stone brick", "cobblestone bricks", "cobble bricks" },
                            { "mossy stone bricks", "some mossy stone brick", "mossy cobblestone bricks", "mossy cobble bricks" },
                            { "cracked stone bricks", "some cracked stone brick", "cracked cobblestone bricks", "cracked cobble bricks" },
                            { "chiseled stone bricks", "some chiseled stone brick", "chiseled cobblestone bricks", "chiseled cobble bricks", "circle blocks" } },
                    { { "giant brown mushroom blocks", "a giant brown mushroom block", "huge brown mushrooms", "big brown mushrooms", "giant brown 'shroom blocks",
                            "huge brown 'shrooms", "big brown shrooms", "giant brown shroom blocks", "huge brown shrooms", "big brown shrooms" } },
                    { { "giant red mushroom blocks", "a giant red mushroom block", "huge red mushrooms", "big red mushrooms", "giant red 'shroom blocks", "huge red 'shrooms",
                            "big red shrooms", "giant red shroom blocks", "huge red shrooms", "big red shrooms" } },
                    { { "iron bars", "some iron bars", "wrought iron bars" } },
                    { { "glass panes", "a glass pane", "windows", "window panes" } },
                    { { "melon blocks", "a melon", "full melons", "watermelon blocks", "whole melons", "whole watermelons" } },
                    { { "pumpkin stems", "a pumpkin stem", "pumpkin stalks", "pumpkin vines" } },
                    { { "melon stems", "a melon stem", "melon stalks", "melon vines", "watermelon stems", "watermelon stalks", "watermelon vines" } },
                    { { "vines", "some vines", "jungle vines", "swamp vines" } },
                    { { "fence gates", "a fence gate", "wooden gates", "wood gates" } },
                    { { "brick stairs", "some brick stairs", "brick steps", "clay brick stairs", "clay brick steps" } },
                    { { "stone brick stairs", "some stone brick stairs", "stone brick steps", "stone stairs", "stone steps" } },
                    { { "mycelium", "some mycelium", "mushroom grass", "shroom grass", "mushroom biome grass" } },
                    { { "lily pads", "a lily pad", "lilies", "pond lilies", "lilypads", "water lily", "water lilies" } },
                    { { "Nether brick blocks", "some Nether brick", "Nether fortress bricks blocks", "Nether dungeon bricks blocks" } },
                    { { "Nether brick fences", "a Nether brick fence post", "Nether fortress fences", "Nether dungeon fences" } },
                    { { "Nether brick stairs", "some Nether brick stairs", "Nether fortress stairs", "Nether dungeon stairs", "Nether brick steps", "Nether fortress steps",
                            "Nether dungeon steps" } },
                    { { "Nether warts", "some Nether warts", "Nether mushrooms", "Nether 'shrooms", "Nether fungi" } },
                    { { "enchantment tables", "an enchantment table" } },
                    { { "brewing stands", "a brewing stand" } },
                    { { "cauldrons", "a cauldron" } },
                    { { "End portal blocks", "an End portal block" } },
                    { { "End portal frame blocks", "an End portal frame block" } },
                    { { "End stone", "some End stone", "End blocks" } },
                    { { "dragon eggs", "a dragon egg", "Enderdragon eggs" } },
                    { { "redstone lamps", "a redstone lamp", "glowstone lamps" } },
                    { { "active redstone lamps", "an active redstone lamp", "active glowstone lamps" } },
                    {
                            { "wooden double slab blocks", "a wooden double slab block", "wooden double slabs", "wooden plank double slab blocks",
                                    "wooden plank double slabs", "wood double slab blocks", "wood double slabs", "wood plank double slab blocks", "wood plank double slabs" },
                            { "oak double slab blocks", "an oak double slab block", "oak double slabs", "oak plank double slab blocks", "oak plank double slabs",
                                    "oak wood double slab blocks", "oak wood double slabs", "oak wood plank double slab blocks", "oak wood plank double slabs" },
                            { "spruce double slab blocks", "a spruce double slab block", "spruce double slabs", "spruce plank double slab blocks",
                                    "spruce plank double slabs", "spruce wood double slab blocks", "spruce wood double slabs", "spruce wood plank double slab blocks",
                                    "spruce wood plank double slabs", "pine double slab blocks", "pine double slabs", "pine plank double slab blocks",
                                    "pine plank double slabs", "pine wood double slab blocks", "pine wood double slabs", "pine wood plank double slab blocks",
                                    "pine wood plank double slabs" },
                            { "birch double slab blocks", "a birch double slab block", "birch double slabs", "birch plank double slab blocks", "birch plank double slabs",
                                    "birch wood double slab blocks", "birch wood double slabs", "birch wood plank double slab blocks", "birch wood plank double slabs" },
                            { "acacia double slab blocks", "a acacia double slab block", "acacia double slabs", "acacia plank double slab blocks",
                                    "acacia plank double slabs", "acacia wood double slab blocks", "acacia wood double slabs", "acacia wood plank double slab blocks",
                                    "acacia wood plank double slabs" },
                            { "dark oak double slab blocks", "a dark oak double slab block", "dark big large huge old ancient oak double slabs",
                                    "dark big large huge old ancient oak plank double slab blocks", "dark big large huge old ancient oak plank double slabs",
                                    "dark big large huge old ancient oak wood double slab blocks", "dark big large huge old ancient oak wood double slabs",
                                    "dark big large huge old ancient oak wood plank double slab blocks", "dark big large huge old ancient oak wood plank double slabs" } },
                    {
                            { "wooden slabs", "a wooden slab", "wooden half blocks", "wood slabs", "wood half blocks", "wooden plank slabs", "wooden plank half blocks",
                                    "wood plank slabs", "wood plank half blocks" },
                            { "oak slabs", "an oak slab", "oak half blocks", "oak wood slabs", "oak wood half blocks", "oak plank slabs", "oak plank half blocks",
                                    "oak wood plank slabs", "oak wood plank half blocks" },
                            { "spruce slabs", "a spruce slab", "spruce half blocks", "spruce wood slabs", "spruce wood half blocks", "spruce plank slabs",
                                    "spruce plank half blocks", "spruce wood plank slabs", "spruce wood plank half blocks", "pine slabs", "pine half blocks",
                                    "pine wood slabs", "pine wood half blocks", "pine plank slabs", "pine plank half blocks", "pine wood plank slabs",
                                    "pine wood plank half blocks" },
                            { "birch slabs", "a birch slab", "birch half blocks", "birch wood slabs", "birch wood half blocks", "birch plank slabs",
                                    "birch plank half blocks", "birch wood plank slabs", "birch wood plank half blocks" },
                            { "acacia slabs", "a acacia slab", "acacia half blocks", "acacia wood slabs", "acacia wood half blocks", "acacia plank slabs",
                                    "acacia plank half blocks", "acacia wood plank slabs", "acacia wood plank half blocks" },
                            { "dark oak slabs", "a dark oak slab", "dark big large huge old ancient oak half blocks", "dark big large huge old ancient oak wood slabs",
                                    "dark big large huge old ancient oak wood half blocks", "dark big large huge old ancient oak plank slabs",
                                    "dark big large huge old ancient oak plank half blocks", "dark big large huge old ancient oak wood plank slabs",
                                    "dark big large huge old ancient oak wood plank half blocks" } },
                    { { "cocoa bean plants", "a cocoa bean plant", "cocoa bean pods", "cocoa beans" } },
                    { { "sandstone stairs", "some sandstone stairs", "sandstone steps" } },
                    { { "emerald ore", "some emerald ore" } },
                    { { "Ender Chests", "an Ender Chest", "Enderchests" } },
                    { { "tripwire hooks", "a tripwire hook", "tripwire mechanisms", "trip wire hooks", "trip wire mechanisms" } },
                    { { "tripwire", "some tripwire", "trip wire" } },
                    { { "emerald blocks", "an emerald block", "blocks of emerald", "blocks of emeralds" } },
                    { { "spruce stairs", "some spruce stairs", "spruce wood stairs", "spruce steps", "spruce wood steps" } },
                    { { "birch stairs", "some birch stairs", "birch wood stairs", "birch steps", "birch wood steps" } },
                    { { "jungle stairs", "some jungle stairs", "jungle wood stairs", "jungle steps", "jungle wood steps" } },
                    { { "command blocks", "a command block" } },
                    { { "beacons", "a beacon" } },
                    {
                            { "cobblestone walls", "a cobblestone wall", "cobblestone fences" },
                            { "mossy cobblestone walls", "a mossy cobblestone wall", "mossy cobblestone fences", "mossy stone walls", "mossy stone fences",
                                    "old cobblestone walls", "old cobblestone fences", "old stone walls", "old stone fences", "ancient cobblestone walls",
                                    "ancient cobblestone fences", "ancient stone walls", "ancient stone fences" } },
                    { { "flower pots", "a flower pot", "pots", "clay pots" } },
                    { { "carrots", "some carrots" } },
                    { { "potatoes", "some potatoes", "potatos" } },
                    { { "wooden buttons", "a wooden button", "wood buttons" } },
                    { { "monster heads", "a monster head", "heads" }, { "skeleton skulls", "a skeleton skull", "skeleton heads", "skele heads", "skele skulls" },
                            { "Wither skeleton skulls", "a Wither skeleton skull", "Wither skeleleton heads", "Wither skele skulls", "Wither skele heads" },
                            { "zombie heads", "a zombie head" },
                            { "Steve heads", "a Steve head", "Minecraft Steve heads", "guy heads", "man heads", "person heads", "human heads" },
                            { "creeper heads", "a creeper head" } },
                    { { "anvils", "an anvil" } },
                    { { "trapped chests", "a trapped chest" } },
                    { { "light weighted pressure plates", "a light weighted pressure plate", "light weight pressure plates", "lightweight pressure plates",
                            "golden pressure plates", "gold pressure plates" } },
                    { { "heavy weighted pressure plates", "a heavy weighted pressure plate", "heavy weight pressure plates", "heavyweight pressure plates",
                            "iron pressure plates", "silver pressure plates" } },
                    { { "redstone comparators", "a redstone comparator", "redstone comparers" } },
                    { { "active redstone comparators", "an active redstone comparator", "active redstone comparers" } },
                    { { "daylight sensors", "a daylight sensor", "night sensors", "nighttime sensors", "day night sensors", "day/night sensors", "daytime nighttime sensors",
                            "daytime/nighttime sensors", "solar panels" } },
                    { { "redstone blocks", "a redstone block", "blocks of redstone dust" } },
                    { { "Nether Quartz ore", "some Nether Quartz ore", "raw Nether Quartz", "crude Nether Quartz", "unrefined Nether Quartz" } },
                    { { "hoppers", "a hopper", "funnels" } },
                    {
                            { "Nether Quartz blocks", "a Nether Quartz block", "a Nether Quartz block", "blocks of Nether Quartz" },
                            { "chiseled Nether Quartz blocks", "a chiseled Nether Quartz block", "chiseled blocks of Nether Quartz", "fancy Nether Quartz blocks",
                                    "fancy blocks of Nether Quartz", "fancy block of Nether Quartz" },
                            { "pillar Nether Quartz blocks", "a pillar Nether Quartz block", "pillar blocks of Nether Quartz" } },
                    { { "Nether Quartz stairs", "some Nether Quartz stairs", "Nether Quartz steps" } },
                    { { "activator rails", "an activator rail", "T.N.T. activator rails", "TNT activator rails", "striker rails", "T.N.T. starter rails", "TNT starter rails" } },
                    { { "droppers", "a dropper", "lazy dispensers", "new dispensers" } },
                    {
                            { "stained clay", "some stained clay", "colored clay", "coloured clay", "dyed clay" },
                            { "white stained clay", "some white stained clay", "white colored clay", "white coloured clay", "white dyed clay" },
                            { "orange stained clay", "some orange stained clay", "orange colored clay", "orange coloured clay", "orange dyed clay" },
                            { "magenta stained clay", "some magenta stained clay", "magenta colored clay", "magenta coloured clay", "magenta dyed clay" },
                            { "light blue stained clay", "some light blue stained clay", "light blue colored clay", "light blue coloured clay", "light blue dyed clay" },
                            { "yellow stained clay", "some yellow stained clay", "yellow colored clay", "yellow coloured clay", "yellow dyed clay" },
                            { "lime green stained clay", "some lime green stained clay", "lime green colored clay", "lime green coloured clay", "lime green dyed clay" },
                            { "pink stained clay", "some pink stained clay", "pink coloured clay", "pink dyed clay" },
                            { "gray stained clay", "some gray stained clay", "gray coloured clay", "gray dyed clay" },
                            { "light gray stained clay", "some light gray stained clay", "light gray colored clay", "light gray coloured clay", "light gray dyed clay" },
                            { "cyan stained clay", "some cyan stained clay", "cyan colored clay", "cyan coloured clay", "cyan dyed clay" },
                            { "purple stained clay", "some purple stained clay", "purple colored clay", "purple coloured clay", "purple dyed clay" },
                            { "blue stained clay", "some blue stained clay", "blue colored clay", "blue coloured clay", "blue dyed clay" },
                            { "brown stained clay", "some brown stained clay", "brown colored clay", "brown coloured clay", "brown dyed clay" },
                            { "cactus green stained clay", "some cactus green stained clay", "dark cactus green stained clay", "cactus green colored clay",
                                    "cactus green coloured clay", "cactus green dyed clay" },
                            { "red stained clay", "some red stained clay", "red colored clay", "red coloured clay", "red dyed clay" },
                            { "black stained clay", "some black stained clay", "black colored clay", "black coloured clay", "black dyed clay" } },
                    {
                            { "stained glass panes", "some stained glass panes", "colored glass panes", "coloured glass panes", "dyed glass panes", "church glass panes",
                                    "tainted glass panes" },
                            { "white stained glass panes", "some white stained glass panes", "white colored glass panes", "white coloured glass panes",
                                    "white dyed glass panes", "white church glass panes", "white tainted glass panes" },
                            { "orange stained glass panes", "some orange stained glass panes", "orange colored glass panes", "orange coloured glass panes",
                                    "orange dyed glass panes", "orange church glass panes", "orange tainted glass panes" },
                            { "magenta stained glass panes", "some magenta stained glass panes", "magenta colored glass panes", "magenta coloured glass panes",
                                    "magenta dyed glass panes", "magenta church glass panes", "magenta tainted glass panes" },
                            { "light blue stained glass panes", "some light blue stained glass panes", "light blue colored glass panes", "light blue coloured glass panes",
                                    "light blue dyed glass panes", "light blue church glass panes", "light blue tainted glass panes" },
                            { "yellow stained glass panes", "some yellow stained glass panes", "yellow colored glass panes", "yellow coloured glass panes",
                                    "yellow dyed glass panes", "yellow church glass panes", "yellow tainted glass panes" },
                            { "lime stained glass panes", "some lime stained glass panes", "lime colored glass panes", "lime coloured glass panes", "lime dyed glass panes",
                                    "lime church glass panes", "lime tainted glass panes" },
                            { "pink stained glass panes", "some pink stained glass panes", "pink colored glass panes", "pink coloured glass panes", "pink dyed glass panes",
                                    "pink church glass panes", "pink tainted glass panes" },
                            { "gray stained glass panes", "some gray stained glass panes", "gray colored glass panes", "gray coloured glass panes", "gray dyed glass panes",
                                    "gray church glass panes", "gray tainted glass panes" },
                            { "light gray stained glass panes", "some light gray stained glass panes", "light gray colored glass panes", "light gray coloured glass panes",
                                    "light gray dyed glass panes", "light gray church glass panes", "light gray tainted glass panes" },
                            { "cyan stained glass panes", "some cyan stained glass panes", "cyan colored glass panes", "cyan coloured glass panes", "cyan dyed glass panes",
                                    "cyan church glass panes", "cyan tainted glass panes" },
                            { "purple stained glass panes", "some purple stained glass panes", "purple colored glass panes", "purple coloured glass panes",
                                    "purple dyed glass panes", "purple church glass panes", "purple tainted glass panes" },
                            { "blue stained glass panes", "some blue stained glass panes", "blue colored glass panes", "blue coloured glass panes", "blue dyed glass panes",
                                    "blue church glass panes", "blue tainted glass panes" },
                            { "brown stained glass panes", "some brown stained glass panes", "brown colored glass panes", "brown coloured glass panes",
                                    "brown dyed glass panes", "brown church glass panes", "brown tainted glass panes" },
                            { "cactus green stained glass panes", "some cactus green stained glass panes", "cactus green colored glass panes",
                                    "cactus green coloured glass panes", "cactus green dyed glass panes", "cactus green church glass panes",
                                    "cactus green tainted glass panes" },
                            { "red stained glass panes", "some red stained glass panes", "red colored glass panes", "red coloured glass panes", "red dyed glass panes",
                                    "red church glass panes", "red tainted glass panes" },
                            { "black stained glass panes", "some black stained glass panes", "black colored glass panes", "black coloured glass panes",
                                    "black dyed glass panes", "black church glass panes", "black tainted glass panes" } },
                    {
                            { "acacia or dark oak leaves", "some acacia or dark oak leaves", "acacia or dark big large huge old ancient oak leaves blocks",
                                    "acacia or dark big large huge old ancient oak leafs blocks" },
                            { "acacia leaves", "some acacia leaves", "acacia leaves blocks", "acacia leafs blocks" },
                            { "dark oak leaves", "some dark oak leaves", "dark big large huge old ancient oak leaves blocks",
                                    "dark big large huge old ancient oak leafs blocks" } },
                    { { "acacia or dark oak logs", "an acacia or dark oak log", "acacia dark big large huge old ancient oak logs wood" },
                            { "acacia logs", "an acacia log", "acacia wood" },
                            { "dark oak logs", "a dark oak log", "dark big large huge old ancient oak logs", "dark big large huge old ancient oak wood" } },
                    { { "acacia stairs", "some acacia stairs", "acacia wood stairs", "acacia wood steps" } },
                    { { "dark oak stairs", "some dark oak stairs", "dark big large huge old ancient oak wood stairs", "dark big large huge old ancient oak wood steps" } },
                    { { "hay bales", "a hay bale", "hay blocks", "wheat block", "horse cow sheep food blocks", "bread blocks" } },
                    { { "carpet", "some carpet", "wool carpeting" }, { "white carpet", "some white carpet", "white wool carpeting" },
                            { "orange carpet", "some orange carpet", "orange wool carpeting" }, { "magenta carpet", "some magenta carpet", "magenta wool carpeting" },
                            { "light blue carpet", "some light blue carpet", "light blue wool carpeting" },
                            { "yellow carpet", "some yellow carpet", "yellow wool carpeting" },
                            { "lime green carpet", "some lime green carpet", "lime green wool carpeting" }, { "pink carpet", "some pink carpet", "pink wool carpeting" },
                            { "dark gray carpet", "some dark gray carpet", "dark gray wool carpeting" },
                            { "light gray carpet", "some light gray carpet", "light gray wool carpeting" }, { "cyan carpet", "some cyan carpet", "cyan wool carpeting" },
                            { "purple carpet", "some purple carpet", "purple wool carpeting" }, { "blue carpet", "some blue carpet", "blue wool carpeting" },
                            { "brown carpet", "some brown carpet", "brown wool carpeting" },
                            { "cactus green carpet", "some cactus green carpet", "cactus green wool carpeting", "dark cactus green carpeting" },
                            { "red carpet", "some red carpet", "red wool carpeting" }, { "black carpet", "some black carpet", "black wool carpeting" } },
                    { { "hardened clay", "some hardened clay", "cooked clay" } },
                    { { "coal blocks", "a block of coal", "blocks of coal" } },
                    { { "packed ice", "some packed ice", "glaciers ice", "glacial ice", "arctic ice", "hard ice", "opaque ice" } },
                    { { "tall flowers", "a tall flower", "double block height flowers", "extra large tall flowers", "two 2 block tall flowers" },
                            { "sunflowers", "a sunflower", "big yellow flowers", "big extra large dandelions" }, { "lilacs", "a lilac", "big pink flowers" },
                            { "very tall grass", "some very tall grass", "super extra tall grass", "high grass" },
                            { "large ferns", "a large fern", "some extra tall large double block height ferns" },
                            { "rose bushes", "a rose bush", "large roses", "roses trees", "roses", "big large tall double height red flowers" },
                            { "peonies", "a peony", "peonys" } },
                    // block I.D.s --> item I.D.s
                    { { "iron shovels", "an iron shovel", "iron spades" } },
                    { { "iron pickaxes", "an iron pickaxe", "iron picks" } },
                    { { "iron axes", "an iron axe", "iron hatchets", "iron tree axe" } },
                    { { "flint and steel", "some flint and steel" } },
                    { { "apples", "an apple", "red apples" } },
                    { { "bows", "a bow", "bows and arrows", "longbows", "long bows", "shortbows", "short bows" } },
                    { { "arrows", "an arrow" } },
                    { { "coal", "a lump of coal" } },
                    { { "diamonds", "a diamond" } },
                    { { "iron", "an iron ingot", "iron ingots" } },
                    { { "gold", "a gold ingot", "gold ingots", "gold bars" } },
                    { { "iron swords", "an iron sword" } },
                    { { "wooden swords", "a woode sword", "wood swords" } },
                    { { "wooden shovels", "a wooden shovel", "wood shovels", "wooden spades", "wood spades" } },
                    { { "wooden pickaxes", "a wooden pickaxe", "wooden picks", "wood pickaxes", "wood picks" } },
                    { { "wooden axes", "a wooden axe", "wooden hatchets", "wooden tree axes", "wood axes", "wood hatchets", "wood tree axes" } },
                    { { "stone swords", "a stone sword", "cobblestone swords", "cobble swords" } },
                    { { "stone shovels", "a stone shovel", "cobblestone shovels", "cobble shovels", "stone spades", "cobblestone spades", "cobble spades" } },
                    { { "stone pickaxes", "a stone pickaxe", "stone picks", "cobblestone pickaxes", "cobble pickaxes", "cobblestone picks", "cobble picks" } },
                    { { "stone axes", "a stone axe", "stone hatchets", "stone tree axes", "cobblestone axes", "cobble axes", "cobblestone hatchets", "cobble hatchets",
                            "cobblestone tree axes", "cobble tree axes" } },
                    { { "diamond swords", "a diamond sword" } },
                    { { "diamond shovels", "a diamond shovel", "diamond spades" } },
                    { { "diamond pickaxes", "a diamond pickaxe", "diamond picks" } },
                    { { "diamond axes", "a diamond axe", "diamond hatchets", "diamond tree axes" } },
                    { { "sticks", "a stick", "twigs" } },
                    { { "bowls", "a bowl", "wooden bowls", "wood bowls", "soup bowls" } },
                    { { "mushroom stew", "a bowl of mushroom stew", "mushroom soup", "mooshroom milk", "mooshroom cow milk" } },
                    { { "golden swords", "a golden sword", "gold swords" } },
                    { { "golden shovels", "a golden shovel", "gold shovels", "golden spades", "gold spades" } },
                    { { "golden pickaxes", "a golden pickaxe", "golden picks", "gold pickaxes", "gold picks" } },
                    { { "golden axes", "a golden axe", "golden hatchets", "golden tree axes", "gold axes", "gold hatchets", "gold tree axes" } },
                    { { "string", "some string" } },
                    { { "feathers", "a feather" } },
                    { { "gunpowder", "some gunpowder", "sulfur", "sulphur" } },
                    { { "wooden hoes", "a wooden hoe", "wood hoes" } },
                    { { "stone hoes", "a stone hoe", "cobblestone hoes", "cobble hoes" } },
                    { { "iron hoes", "an iron hoe" } },
                    { { "diamond hoes", "a diamond hoe" } },
                    { { "golden hoes", "a golden hoe", "gold hoes" } },
                    { { "seeds", "some seeds", "seed packets" } },
                    { { "wheat", "some wheat", "crops" } },
                    { { "bread", "a loaf of bread", "bread loaves" } },
                    { { "leather caps", "a leather cap", "leather helmets", "leather helms" } },
                    { { "leather tunics", "a leather tunic", "leather shirts", "leather chestplates" } },
                    { { "leather pants", "a pair of leather pants", "leather leggings", "leather chaps" } },
                    { { "leather boots", "a pair of leather boots", "leather shoes" } },
                    { { "chainmail helmets", "a chainmail helmet", "chainmail caps", "chainmail helms", "chain helmets", "chain caps", "chain helms" } },
                    { { "chainmail chestplates", "a chainmail chestplate", "chainmail tunics", "chainmail shirts", "chain chestplates", "chain tunics", "chain shirts" } },
                    { { "chainmail leggings", "some chainmail leggings", "chainmail pants", "chain leggings", "chain pants" } },
                    { { "chainmail boots", "a pair of chainmail boots", "chainmail shoes", "chain boots", "chain shoes" } },
                    { { "iron helmets", "an iron helmet", "iron caps", "iron helms" } },
                    { { "iron chestplates", "an iron chestplate", "iron tunics", "iron shirts" } },
                    { { "iron leggings", "some iron leggings", "iron pants" } },
                    { { "iron boots", "a pair of iron boots", "iron shoes" } },
                    { { "diamond helmets", "a diamond helmet", "diamond caps", "diamond helms" } },
                    { { "diamond chestplates", "a diamond chestplate", "diamond tunics", "diamond shirts" } },
                    { { "diamond leggings", "some diamond leggings", "diamond pants" } },
                    { { "diamond boots", "a pair of diamond boots", "diamond shoes" } },
                    { { "golden helmets", "a golden helmet", "golden caps", "golden helms", "gold helmets", "gold caps", "gold helms" } },
                    { { "golden chestplates", "a golden chestplate", "gold chestplates", "golden tunics", "gold tunics", "golden shirts", "gold shirts" } },
                    { { "golden leggings", "some golden leggings", "gold leggings", "golden pants", "gold pants" } },
                    { { "golden boots", "a pair of golden boots", "gold boots", "golden shoes", "gold shoes" } },
                    { { "flint", "a piece of flint", "arrowheads" } },
                    { { "raw porkchops", "a raw porkchop", "uncooked porkchops" } },
                    { { "cooked porkchops", "a cooked porkchop", "porkchops" } },
                    { { "paintings", "a painting", "artwork" } },
                    {
                            { "golden apples", "a golden apple", "gold apples" },
                            { "enchanted golden apples", "an enchanted golden apple", "enchanted gold apples", "magic golden apples", "magic gold apples",
                                    "shiny golden apples", "shiny gold apples", "shining golden apples", "shiny golden apples" } },
                    { { "signs", "a sign", "sign posts", "posted signs", "wall signs" } },
                    { { "wooden doors", "a wooden door", "wood doors" } },
                    { { "buckets", "a bucket", "pails" } },
                    { { "buckets of water", "a bucket of water", "water buckets" } },
                    { { "buckets of lava", "a bucket of lava", "lava buckets" } },
                    { { "minecarts", "a minecart", "mine carts", "minecars", "mine cars", "rail cars" } },
                    { { "saddles", "a saddle", "pig saddles" } },
                    { { "iron doors", "an iron door", "metal doors" } },
                    { { "redstone dust", "some redstone dust", "redstone powder", "redstone" } },
                    { { "snowballs", "a snow ball" } },
                    { { "boats", "a boat", "wooden boats", "wood boats", "rafts", "wood rafts", "wooden rafts" } },
                    { { "leather", "some leather", "cow hides", "cow skin", "cowskin" } },
                    { { "milk", "some milk", "leche", "bucket of milk", "buckets of milk", "pail of milk", "pails of milk" } },
                    { { "bricks", "a brick", "clay bricks" } },
                    { { "clay", "a piece of clay" } },
                    { { "sugarcane", "some sugarcane", "sugarcanes", "sugar canes" } },
                    { { "papers", "a piece of paper" } },
                    { { "books", "a book" } },
                    { { "slimeballs", "a slimeball" } },
                    { { "storage minecarts", "a storage minecart", "storage minecars", "storage mine cars", "storage rail cars", "chest minecarts", "chest minecars",
                            "chest mine cars", "chest rail cars", "minecarts with chests", "minecars with chests", "mine cars with chests", "rail cars with chests" } },
                    { { "powered minecarts", "a powered minecart", "powered minecars", "powered mine cars", "powered rail cars", "furnace minecarts", "furnace minecars",
                            "furnace mine cars", "furnace rail cars", "minecarts with furnaces", "minecars with furnaces", "mine cars with furnaces",
                            "rail cars with furnaces" } },
                    { { "eggs", "an egg", "chicken eggs" } },
                    { { "compasses", "a compass" } },
                    { { "fishing rods", "a fishing rod", "fishing poles" } },
                    { { "clocks", "a clock", "watches", "pocketwatches", "pocket watches" } },
                    { { "glowstone dust", "some glowstone dust" } },
                    { { "all raw fish", "a raw fish" },
                            { "raw cod", "a raw cod", "uncooked cod", "uncooked plain regular normal fish", "raw plain regular normal fish", "raw uncooked green fish" },
                            { "raw salmon", "a raw salmon", "uncooked salmon", "raw uncooked red fish" },
                            { "clownfish", "a clownfish", "raw clownfish", "anemonefish", "Nemo fish", "raw uncooked orange fish" },
                            { "pufferfish", "a pufferfish", "poisonfish", "water breathing fish", "balloonfish", "raw uncooked yellow fish" } },
                    { { "all cooked fish", "a cooked fish" }, { "cooked cod", "a cooked cod", "cooked plain regular normal fish" },
                            { "cooked salmon", "a cooked salmon", "cooked red fish" } },
                    {
                            { "dyes", "some dye", "wool dyes" },
                            { "ink sacks", "an ink sack", "squid ink sacks", "squid ink sackks", "squid ink pods", "black wool dyes" },
                            { "red dye", "some red dye", "rose red wool dyes" },
                            { "cactus green dye", "some cactus green dye", "cactus green dyes", "cactus green wool dyes" },
                            { "cocoa beans", "some cocoa beans", "chocolate beans", "brown dyes", "brown wool dyes" },
                            { "lapis lazuli", "a piece of lapis lazuli", "lapis lazuli dyes", "lapis lazuli wool dyes", "lapis dyes", "lapis wool dyes", "blue dyes",
                                    "blue wool dyes", "dark blue dyes", "dark blue wool dyes" },
                            { "purple dye", "some purple dye", "purple dyes", "purple wool dyes" },
                            { "cyan dye", "some cyan dye", "cyan dyes", "cyan wool dyes" },
                            { "light gray dye", "some light gray dye", "light gray dyes", "light gray wool dyes", "light grey dyes", "light grey wool dyes" },
                            { "gray dye", "some gray dye", "dark gray dyes", "dark gray wool dyes", "dark grey dyes", "dark grey wool dyes" },
                            { "pink dye", "some pink dye", "pink dyes", "pink wool dyes", "light red dyes", "light red wool dyes" },
                            { "bright green dye", "some bright green dye", "bright green dyes", "lime dyes", "lime wool dyes", "lime green dyes", "lime green wool dyes",
                                    "green dyes", "green wool dyes" },
                            { "yellow dye", "some yellow dye", "yellow dyes", "yellow wool dyes", "yellow flower dyes", "yellow flower wool dyes", "dandelion yellow dyes",
                                    "dandelion yellow wool dyes", "yellow dandelion dyes", "yellow dandelion wool dyes" },
                            { "light blue dye", "light blue dyes", "light blue wool dyes" }, { "magenta dye", "some magenta dye", "magenta dyes", "magenta wool dyes" },
                            { "orange dye", "orange dyes", "orange wool dyes" },
                            { "bone meal", "some bone meal", "bone meals", "bonemeals", "white dyes", "white wool dyes", "wool bleaches" } },
                    { { "bones", "a bone" } },
                    { { "sugar", "some sugar", "processed sugar", "powdered sugar", "raw sugar", "baker's sugar" } },
                    { { "cakes", "a cake", "birthday cakes" } },
                    { { "beds", "a bed" } },
                    { { "repeaters", "a repeater", "diodes", "delayers", "redstone repeaters", "redstone diodes", "redstone delayers" } },
                    { { "cookies", "a cookie", "chocolate chip cookies", "oatmeal raisin cookies" } },
                    { { "maps", "a map", "atlases", "charts" } },
                    { { "shears", "some shears", "clippers" } },
                    { { "melon slices", "a melon slice", "slices of melon" } },
                    { { "pumpkin seeds", "some pumpkin seeds" } },
                    { { "melon seeds", "some melon seeds" } },
                    { { "raw beef", "a hunk of raw beef", "uncooked beef", "uncooked steak" } },
                    { { "steak", "a steak", "beef", "cooked beef" } },
                    { { "raw chickens", "a raw chicken", "uncooked chickens" } },
                    { { "cooked chickens", "a cooked chicken", "chickens" } },
                    { { "rotten flesh", "some rotten flesh", "rotted flesh", "flesh", "zombie flesh", "zombie meat" } },
                    { { "Ender Pearls", "an Ender Pearl", "Enderpearls", "Enderman Pearls" } },
                    { { "Blaze rods", "a Blaze rod", "glowsticks", "glow sticks" } },
                    { { "Ghast tears", "a Ghast tear", "tears" } },
                    { { "gold nuggets", "a gold nugget", "golden nuggets", "gold pieces", "pieces of gold" } },
                    { { "Nether warts", "some Nether warts", "Nether mushrooms", "Nether 'shrooms", "Nether fungi" } },
                    {
                            { "potions", "a potion" },
                            { "water bottles", "a water bottle", "canteens" },
                            { "Awkward Potions", "an Awkward Potion", "useless potions", "lame potions" },
                            { "Thick Potions", "a Thick Potion", "pots potions of thickness" },
                            { "Mundane Potions", "a Mundane Potion", "pots potions of mundaneness" },
                            { "Potions of Regeneration", "a Potion of Regeneration", "pots potions of regeneration" },
                            { "Potions of Swiftness", "a Potion of Swiftness", "pots potions of swiftness sprinting running fast" },
                            { "Potions of Fire Resistance", "a Potion of Fire Resistance",
                                    "pots potions of no burning fire resistance lava swimming fireproof inflammable inflammability" },
                            { "Potions of Poison", "a Potion of Poison", "pots potions of poison toxic toxins" },
                            { "Potions of Healing", "a Potion of Healing", "pots potions of instant healing instaheal instahealth" },
                            { "Potions of Night Vision", "a Potion of Night Vision", "pots potions of nightvision" },
                            null,
                            { "Potions of Weakness", "a Potion of Weakness", "pots potions of weakness fraility frailness fragility fragile easily hurt" },
                            { "Potions of Strength", "a Potion of Strength",
                                    "pots potions of super strength strong extra damage sword superman superwoman supergirl wonderwoman" },
                            { "Potions of Slowness", "a Potion of Slowness", "pots potions of slowness sloth laziness slow down slowing" },
                            null,
                            { "Potions of Harming", "a Potion of Harming", "pots potions of instaharming instahurting instapain instahealth loss" },
                            { "Potions of Water Breathing", "a Potion of Water Breathing", "pots potions of water breathing mermaid's breath" },
                            { "Potions of Invisibility", "a Potion of Invisibility", "pots potions of invisibility invisible no see clear hiding hidden pranking" },
                            { "Potions of Regeneration II", "a Potion of Regeneration II", "pots potions of regeneration II 2 two" },
                            { "Potions of Swiftness II", "a Potion of Swiftness II", "pots potions of swiftness sprinting running fast II 2 two" },
                            null,
                            { "Potions of Poison II", "a Potion of Poison II", "pots potions of poison toxic toxins II 2 two" },
                            { "Potions of Healing II", "a Potion of Healing II", "pots potions of instant healing instaheal instahealth II 2 two" },
                            { "Potions of Strength II", "a Potion of Strength II",
                                    "pots potions of super strength strong extra damage sword superman superwoman supergirl wonderwoman II 2 two" },
                            null,
                            null,
                            { "Potions of Harming II", "a Potion of Harming II", "pots potions of instaharming instahurting instapain instahealth loss II 2 two" },
                            { "Potions of Regeneration Extended", "a Potion of Regeneration Extended", "pots potions of regeneration Extended" },
                            { "Potions of Swiftness Extended", "a Potion of Swiftness Extended", "pots potions of swiftness sprinting running fast Extended" },
                            { "Potions of Fire Resistance Extended", "a Potion of Fire Resistance Extended",
                                    "pots potions of no burning fire resistance lava swimming fireproof inflammable inflammability Extended" },
                            { "Potions of Poison Extended", "a Potion of Poison Extended", "pots potions of poison toxic toxins Extended" },
                            null,
                            { "Potions of Night Vision Extended", "a Potion of Night Vision Extended", "pots potions of nightvision Extended" },
                            null,
                            { "Potions of Weakness Extended", "a Potion of Weakness Extended",
                                    "pots potions of weakness fraility frailness fragility fragile easily hurt Extended" },
                            { "Potions of Strength Extended", "a Potion of Strength Extended",
                                    "pots potions of super strength strong extra damage sword superman superwoman supergirl wonderwoman Extended" },
                            { "Potions of Slowness Extended", "a Potion of Slowness Extended", "pots potions of slowness sloth laziness slow down slowing Extended" },
                            null,
                            null,
                            { "Potions of Water Breathing Extended", "a Potion of Water Breathing Extended", "pots potions of water breathing mermaid's breath Extended" },
                            { "Potions of Invisibility Extended", "a Potion of Invisibility Extended",
                                    "pots potions of invisibility invisible no see clear hiding hidden pranking Extended" },
                            { "Potions of Regeneration II Extended", "a Potion of Regeneration II Extended", "pots potions of regeneration II 2 two Extended" },
                            { "Potions of Swiftness II Extended", "a Potion of Swiftness II Extended", "pots potions of swiftness sprinting running fast II 2 two Extended" },
                            null,
                            { "Potions of Poison II Extended", "a Potion of Poison II Extended", "pots potions of poison toxic toxins II 2 two Extended" },
                            { "Potions of Strength II Extended", "a Potion of Strength II Extended",
                                    "pots potions of super strength strong extra damage sword superman superwoman supergirl wonderwoman II 2 two Extended" },
                            { "Splash Potions of Regeneration", "a Splash Potion of Regeneration", "pots splash thrown potions of regeneration" },
                            { "Splash Potions of Swiftness", "a Splash Potion of Swiftness", "pots splash thrown potions of swiftness sprinting running fast" },
                            { "Splash Potions of Fire Resistance", "a Splash Potion of Fire Resistance",
                                    "pots splash thrown potions of no burning fire resistance lava swimming fireproof inflammable inflammability" },
                            { "Splash Potions of Poison", "a Splash Potion of Poison", "pots splash thrown potions of poison toxic toxins" },
                            { "Splash Potions of Healing", "a Splash Potion of Healing", "pots splash thrown potions of instant healing instaheal instahealth" },
                            { "Splash Potions of Night Vision", "a Splash Potion of Night Vision", "pots splash thrown potions of nightvision" },
                            null,
                            { "Splash Potions of Weakness", "a Splash Potion of Weakness",
                                    "pots splash thrown potions of weakness fraility frailness fragility fragile easily hurt" },
                            { "Splash Potions of Strength", "a Splash Potion of Strength",
                                    "pots splash thrown potions of super strength strong extra damage sword superman superwoman supergirl wonderwoman" },
                            { "Splash Potions of Slowness", "a Splash Potion of Slowness", "pots splash thrown potions of slowness sloth laziness slow down slowing" },
                            null,
                            { "Splash Potions of Harming", "a Splash Potion of Harming", "pots splash thrown potions of instaharming instahurting instapain instahealth loss" },
                            { "Splash Potions of Water Breathing", "a Splash Potion of Water Breathing", "pots splash thrown potions of water breathing mermaid's breath" },
                            { "Splash Potions of Invisibility", "a Splash Potion of Invisibility",
                                    "pots splash thrown potions of invisibility invisible no see clear hiding hidden pranking" },
                            { "Splash Potions of Regeneration II", "a Splash Potion of Regeneration II", "pots splash thrown potions of regeneration II 2 two" },
                            { "Splash Potions of Swiftness II", "a Splash Potion of Swiftness II", "pots splash thrown potions of swiftness sprinting running fast II 2 two" },
                            null,
                            { "Splash Potions of Poison II", "a Splash Potion of Poison II", "pots splash thrown potions of poison toxic toxins II 2 two" },
                            { "Splash Potions of Healing II", "a Splash Potion of Healing II", "pots splash thrown potions of instant healing instaheal instahealth II 2 two" },
                            { "Splash Potions of Strength II", "a Splash Potion of Strength II",
                                    "pots splash thrown potions of super strength strong extra damage sword superman superwoman supergirl wonderwoman II 2 two" },
                            null,
                            null,
                            { "Splash Potions of Harming II", "a Splash Potion of Harming II",
                                    "pots splash thrown potions of instaharming instahurting instapain instahealth loss II 2 two" },
                            { "Splash Potions of Regeneration Extended", "a Splash Potion of Regeneration Extended", "pots splash thrown potions of regeneration Extended" },
                            { "Splash Potions of Swiftness Extended", "a Splash Potion of Swiftness Extended",
                                    "pots splash thrown potions of swiftness sprinting running fast Extended" },
                            { "Splash Potions of Fire Resistance Extended", "a Splash Potion of Fire Resistance Extended",
                                    "pots splash thrown potions of no burning fire resistance lava swimming fireproof inflammable inflammability Extended" },
                            { "Splash Potions of Poison Extended", "a Splash Potion of Poison Extended", "pots splash thrown potions of poison toxic toxins Extended" },
                            null,
                            { "Splash Potions of Night Vision Extended", "a Splash Potion of Night Vision Extended", "pots splash thrown potions of nightvision Extended" },
                            null,
                            { "Splash Potions of Weakness Extended", "a Splash Potion of Weakness Extended",
                                    "pots splash thrown potions of weakness fraility frailness fragility fragile easily hurt Extended" },
                            { "Splash Potions of Strength Extended", "a Splash Potion of Strength Extended",
                                    "pots splash thrown potions of super strength strong extra damage sword superman superwoman supergirl wonderwoman Extended" },
                            { "Splash Potions of Slowness Extended", "a Splash Potion of Slowness Extended",
                                    "pots splash thrown potions of slowness sloth laziness slow down slowing Extended" },
                            null,
                            null,
                            { "Splash Potions of Water Breathing Extended", "a Splash Potion of Water Breathing Extended",
                                    "pots splash thrown potions of water breathing mermaid's breath Extended" },
                            { "Splash Potions of Invisibility Extended", "a Splash Potion of Invisibility Extended",
                                    "pots splash thrown potions of invisibility invisible no see clear hiding hidden pranking Extended" },
                            { "Splash Potions of Regeneration II Extended", "a Splash Potion of Regeneration II Extended",
                                    "pots splash thrown potions of regeneration II 2 two Extended" },
                            { "Splash Potions of Swiftness II Extended", "a Splash Potion of Swiftness II Extended",
                                    "pots splash thrown potions of swiftness sprinting running fast II 2 two Extended" },
                            null,
                            { "Splash Potions of Poison II Extended", "a Splash Potion of Poison II Extended",
                                    "pots splash thrown potions of poison toxic toxins II 2 two Extended" },
                            { "Splash Potions of Strength II Extended", "a Splash Potion of Strength II Extended",
                                    "pots splash thrown potions of super strength strong extra damage sword superman superwoman supergirl wonderwoman II 2 two Extended" } },
                    { { "glass bottles", "a glass bottle" } },
                    { { "spider eyes", "a spider eye" } },
                    { { "fermented spider eyes", "a fermented spider eye" } },
                    { { "Blaze powder", "some Blaze powder" } },
                    { { "Magma Cream", "some Magma Cream" } },
                    { { "brewing stands", "a brewing stand" } },
                    { { "cauldrons", "a cauldron", "kettles" } },
                    { { "Eyes of Ender", "an Eye of Ender", "Endereyes" } },
                    { { "glistening melon", "a glistening melon", "glistening melon slices", "gold melon slices", "golden melon slices", "shining melon slices" } },
                    { { "spawn eggs", "a spawn egg", "spawner spawning eggs" }, { "creeper spawn eggs", "a creeper spawn egg", "creeper spawner spawning eggs" },
                            { "skeleton spawn eggs", "a skeleton spawn egg", "skeleton spawner spawning eggs" },
                            { "spider spawn eggs", "a spider spawn egg", "spider spawner spawning eggs" }, null,
                            { "zombie spawn eggs", "a zombie spawn egg", "human regular old zombies spawner spawning eggs" },
                            { "slime spawn eggs", "a slime spawn egg", "slime spawner spawning eggs" },
                            { "Ghast spawn eggs", "a Ghast spawn egg", "Ghast spawner spawning eggs" },
                            { "zombie pigman spawn eggs", "a zombie pigman spawn egg", "zombie zombified pigman pigmen spawner spawning eggs" },
                            { "Enderman spawn eggs", "an Enderman spawn egg", "Enderman Endermen spawner spawning eggs" },
                            { "cave spider spawn eggs", "a cave spider spawn egg", "cave spiders spawner spawning eggs" },
                            { "silverfish spawn eggs", "a silverfish spawn egg", "silverfish spawner spawning eggs" },
                            { "Blaze spawn eggs", "a Blaze spawn egg", "Blazes spawner spawning eggs" },
                            { "Magma Cube spawn eggs", "a Magma Cube spawn egg", "Magma Cubes spawner spawning eggs" }, null, null,
                            { "bat spawn eggs", "a bat spawn egg", "bats spawner spawning eggs" },
                            { "witch spawn eggs", "a witch spawn egg", "witches spawner spawning eggs" },
                            { "pig spawn eggs", "a pig spawn egg", "pigs piggies spawner spawning eggs" },
                            { "sheep spawn eggs", "a sheep spawn egg", "sheeps spawner spawning eggs" },
                            { "cow spawn eggs", "a cow spawn egg", "cows calfs calves spawner spawning eggs" },
                            { "chicken spawn eggs", "a chicken spawn egg", "chickens chicks spawner spawning eggs" },
                            { "squid spawn eggs", "a squid spawn egg", "squids spawner spawning eggs" },
                            { "wolf spawn eggs", "a wolf spawn egg", "wolfs wolves dogs spawner spawning eggs" },
                            { "mooshroom spawn eggs", "a mooshroom spawn egg", "mooshrooms cows calfs calves spawner spawning eggs" }, null,
                            { "ocelot spawn eggs", "an ocelot spawn egg", "ocelots cats kitties kittens spawner spawning eggs" },
                            { "villager spawn eggs", "a villager spawn egg", "villagers N.P.C. Testificates spawner spawning eggs" } },
                    { { "Bottles o' Enchanting", "a Bottle o' Enchanting", "xp bottles", "exp bottles", "level botties", "experience bottles" } },
                    { { "fire charges", "a fire charge", "fireballs", "cannonballs", "Ghast cannonballs", "Blaze cannonballs", "Ghast fireballs", "Blaze fireballs" } },
                    { { "books and quills", "a book and quill", "book and quill" } },
                    { { "written-in books", "a written-in book", "novels", "texts" } },
                    { { "emeralds", "an emerald" } },
                    { { "item frames", "an item frame", "frames" } },
                    { { "flower pots", "a flower pot", "pots", "potted flowers plants" } },
                    { { "carrots", "a carrot" } },
                    { { "potatoes", "a potato", "raw potatoes" } },
                    { { "baked potatoes", "a baked potato", "cooked potatoes", "mashed potatoes" } },
                    { { "poisonous potatoes", "a poisonous potato", "poison potatoes", "bad potatoes" } },
                    { { "maps", "a map", "charts", "atlases" } },
                    { { "golden carrots", "a golden carrot", "gold carrots", "glistening carrots", "shiny carrots" } },
                    { { "monster heads", "a monster head", "heads" }, { "skeleton skulls", "a skeleton skull", "skeleton heads", "skele heads", "skele skulls" },
                            { "Wither skeleton skulls", "a Wither skeleton skull", "Wither skeleleton heads", "Wither skele skulls", "Wither skele heads" },
                            { "zombie heads", "a zombie head" },
                            { "Steve heads", "a Steve head", "Minecraft Steve heads", "guy heads", "man heads", "person heads", "human heads" },
                            { "creeper heads", "a creeper head" } },
                    { { "carrots on sticks", "a carrot on a stick", "carrots on fishing rods", "carrots on fishing poles", "pig controller" } },
                    { { "Nether Stars", "a Nether star" } },
                    { { "pumpkin pies", "a pumpkin pie" } },
                    { { "fireworks", "a firework", "firework rockets" } },
                    { { "firework stars", "a firework star", "firework color effect balls" } },
                    { { "enchanted books", "an enchanted book", "magic spellbooks" } },
                    { { "redstone comparators", "a redstone comparator", "redstone comparers" } },
                    { { "Nether bricks", "a Nether brick", "individual single singular Nether bricks" } },
                    { { "Nether Quartz", "some Nether Quartz", "Nether gems" } },
                    { { "T.N.T. minecarts", "a T.N.T. minecart", "TNT trinitrotoluene minecarts" } },
                    { { "hopper minecarts", "a hopper minecart", "vacuum pickup minecarts" } },
                    { { "sets of iron horse armor", "a set of iron horse armor" } },
                    { { "sets of gold horse armor", "a set of gold horse armor", "sets of golden horse armor" } },
                    { { "sets of diamond horse armor", "a set of diamond horse armor" } },
                    { { "leads", "a lead", "mob animal leads leashes" } },
                    { { "name tags", "a name tag", "dog tags", "name plates", "nameplates" } },
                    { { "command block minecarts", "a command block minecart", "command block mine carts", "command block minecars", "command block mine cars",
                            "command block rail cars" } }, { { "\"13\" music discs", "a \"13\" music disc", "\"13\" disks", "\"13\" records", "\"13\" CDs" } },
                    { { "\"cat\" music discs", "\"cat\" disks", "\"cat\" records", "\"cat\" CDs" } },
                    { { "\"blocks\" music discs", "a \"blocks\" music disc", "\"blocks\" disks", "\"blocks\" records", "\"blocks\" CDs" } },
                    { { "\"chirp\" music discs", "\"chirp\" disks", "\"chirp\" records", "\"chirp\" CDs" } },
                    { { "\"far\" music discs", "a \"chirp\" music disc", "\"far\" disks", "\"far\" records", "\"far\" CDs" } },
                    { { "\"mall\" music discs", "a \"mall\" music disc", "\"mall\" disks", "\"mall\" records", "\"mall\" CDs" } },
                    { { "\"mellohi\" music discs", "a \"mellohi\" music disc", "\"mellohi\" disks", "\"mellohi\" records", "\"mellohi\" CDs" } },
                    { { "\"stal\" music discs", "a \"stal\" music disc", "\"stal\" disks", "\"stal\" records", "\"stal\" CDs" } },
                    { { "\"strad\" music discs", "a \"strad\" music disc", "\"strad\" disks", "\"strad\" records", "\"strad\" CDs" } },
                    { { "\"ward\" music discs", "a \"ward\" music disc", "\"ward\" disks", "\"ward\" records", "\"ward\" CDs" } },
                    { { "\"11\" music discs", "an \"11\" music disc", "\"11\" disks", "\"11\" records", "\"11\" CDs" } },
                    { { "\"wait\" music discs", "\"wait\" disks", "\"wait\" records", "\"wait\" CDs" } } };

    // color coding info
    public static final char[] COLOR_CODE_CHARS = { '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f', 'k', 'l', 'm', 'n', 'o', 'r' };
    public static final char[] COLOR_COLOR_CODE_CHARS = { '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f' };
    public static final char[] FORMATTING_COLOR_CODE_CHARS = { 'k', 'l', 'm', 'n', 'o', 'r' };
    public static final String[] MINECRAFT_COLORS = { "black", "red", "green", "brown", "blue", "purple", "cyan", "light gray", "gray", "pink", "lime", "yellow",
            "light blue", "magenta", "orange", "white" };

    // liquid breakage properties
    public static final short[] CAN_BE_BROKEN_BY_LIQUIDS_IDS = { 0, 27, 28, 30, 31, 32, 37, 38, 39, 40, 50, 51, 55, 59, 66, 69, 75, 76, 78, 93, 94, 104, 105, 106, 115, 127,
            131, 132, 140, 141, 142, 144, 149, 150, 157 };

    // blocks with abnormal heights
    public static final short[] FENCE_HEIGHT_BLOCK_IDS = { 85, 107, 139 };
    public static final short[] SOLID_PARTIAL_HEIGHT_BLOCK_IDS = { 44, 93, 94, 96, 111, 126, 149, 150, 151 };

    // lockable blocks
    public static final short[] LOCKABLE_CONTAINER_IDS = { 23, 54, -58, 61, 62, 84, -116, 117, 130, 137, 138, -145, 146, 154, 158 };
    public static final short[] LOCKABLE_PORTAL_IDS = { 64, 71, 96, 107 };
    public static final short[] LOCKABLE_SWITCH_IDS = { 28, 69, 70, 72, 77, 143, 147, 148 };

    // blocks that must be attached to other blocks
    public static final short[] MUST_BE_ATTACHED_BOTTOM_ONLY_IDS = { 6, 26, 27, 28, 31, 32, 37, 38, 39, 40, 55, 59, 63, 64, 66, 70, 71, 72, 78, 81, 83, 93, 94, 104, 105, 111,
            115, 132, 140, 147, 148, 149, 150, 157 };
    public static final short[] MUST_BE_ATTACHED_CAN_BE_SIDEWAYS_IDS = { 50, 65, 68, 69, 75, 76, 77, 96, 106, 127, 131 };

    // physical block types
    public static final short[] NON_SOLID_BLOCK_IDS = { 0, 6, 27, 28, 30, 31, 32, 37, 38, 39, 40, 50, 51, 55, 59, 63, 64, 65, 66, 68, 69, 70, 71, 72, 75, 76, 77, 78, 83, 90,
            93, 94, 104, 105, 115, 119, 131, 132, 140, 141, 142, 142, 144, 147, 148, 149, 150, 157, 171, 175 };
    public static final short[] LIQUID_BLOCK_IDS = { 8, 9, 10, 11 };

    // tool repairing info
    public static final short[][] DAMAGEABLE_ITEM_IDS = { { 256, 265 }, { 257, 265 }, { 258, 265 }, { 259 }, { 261 }, { 267, 265 }, { 268, 5 }, { 269, 5 }, { 270, 5 },
            { 271, 5 }, { 272, 4 }, { 273, 4 }, { 274, 4 }, { 275, 4 }, { 276, 264 }, { 277, 264 }, { 278, 264 }, { 279, 264 }, { 283, 266 }, { 284, 266 }, { 285, 266 },
            { 286, 266 }, { 290, 5 }, { 291, 4 }, { 292, 265 }, { 293, 264 }, { 294, 266 }, { 298, 334 }, { 299, 334 }, { 300, 334 }, { 301, 334 }, { 302, 265 },
            { 303, 265 }, { 304, 265 }, { 305, 265 }, { 306, 265 }, { 307, 265 }, { 308, 265 }, { 309, 265 }, { 310, 264 }, { 311, 264 }, { 312, 264 }, { 313, 264 },
            { 314, 266 }, { 315, 266 }, { 316, 266 }, { 317, 266 }, { 346 }, { 359 }, { 398 } };

    // gaps for all the data structures
    public static final short[][] ENCHANTMENT_GAPS = { { 7, 16 }, { 21, 32 }, { 35, 48 }, { 51, 61 } };
    public static final short[][] ENTITY_GAPS = { { 2, 8 }, { 22, 41 }, { 66, 90 }, { 99, 120 }, { 120, 200 } };
    public static final short[][] ITEM_GAPS = { { 164, 170 }, { 175, 256 }, { 408, 417 }, { 422, 2256 } };
    public static final short[][] POTION_DATA_GAPS = { { 0, 16 }, { 16, 32 }, { 32, 64 }, { 64, 8193 }, { 8206, 8225 }, { 8229, 8233 }, { 8236, 8257 }, { 8270, 8289 },
            { 8292, 8297 }, { 8297, 16385 }, { 16398, 16417 }, { 16421, 16425 }, { 16428, 16449 }, { 16462, 16481 }, { 16484, 16489 } };
    public static final short[][] SPAWN_EGG_DATA_GAPS = { { -1, 50 }, { 66, 90 }, { 98, 120 } };
}